name: SAST - C/C++

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake clang clang-tidy cppcheck python3

      - name: Configure + Build (CMake)
        run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Unix Makefiles"
          cmake --build build

      - name: Run all SAST tools
        run: |
          chmod +x ./run_all_sast.sh
          ./run_all_sast.sh

      - name: Run demo script (SARIF conversion)
        run: |
          chmod +x ./demo_run_sast.sh
          ./demo_run_sast.sh

      - name: Upload textual reports
        uses: actions/upload-artifact@v4
        with:
          name: sast-reports
          path: sast-reports/

      - name: Upload merged SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sast-reports/merged.sarif

